"""Build static index files for the creditmacro research corpus.

Deliverables generated:
  docs/markdowns-index.md   — sorted list of all *.md in markdowns/ (immutable raw sources)
  docs/investment-memos-index.md — memos ingested into wiki/sources/, grouped by publisher

Run as a standalone script:
    python3 tools/build_indexes.py

Or import and call main() from another script.
"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path
from typing import Optional

# Allow direct-script invocation.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

_REPO_ROOT = Path(__file__).resolve().parent.parent
_MARKDOWNS_DIR = _REPO_ROOT / "markdowns"
_WIKI_SOURCES_DIR = _REPO_ROOT / "wiki" / "sources"
_DOCS_DIR = _REPO_ROOT / "docs"

# Publisher prefixes in the order we want them grouped (matches the registry keys).
_PUBLISHER_ORDER = [
    "oaktree",
    "applied-macro",
    "noahpinion",
    "apricitas",
    "the-overshoot",
    "net-interest",
    "petition",
    "debt-serious",
    "jill-cetina",
]


def _human_size(n_bytes: int) -> str:
    """Return a human-readable file size string."""
    for unit in ("B", "KB", "MB", "GB"):
        if n_bytes < 1024:
            return f"{n_bytes:.0f} {unit}"
        n_bytes /= 1024
    return f"{n_bytes:.1f} GB"


def _extract_frontmatter_field(text: str, field: str) -> Optional[str]:
    """Extract a single YAML frontmatter field value (simple regex, no full YAML parse)."""
    m = re.search(r"^" + re.escape(field) + r":\s*(.*)", text, re.MULTILINE)
    if not m:
        return None
    val = m.group(1).strip()
    # Strip surrounding quotes (single or double).
    if (val.startswith("'") and val.endswith("'")) or (
        val.startswith('"') and val.endswith('"')
    ):
        val = val[1:-1]
    return val or None


def _parse_source_card(path: Path) -> Optional[dict]:
    """Return frontmatter dict for a wiki source card, or None if unparseable."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None
    m = re.match(r"^---\n(.*?)\n---", text, re.DOTALL)
    if not m:
        return None
    fm = m.group(1)
    return {
        "file": path.name,
        "title": _extract_frontmatter_field(fm, "title") or path.stem,
        "slug": _extract_frontmatter_field(fm, "slug") or path.stem,
        "access_class": _extract_frontmatter_field(fm, "access_class") or "",
        "source_type": _extract_frontmatter_field(fm, "source_type") or "",
        "source_date": _extract_frontmatter_field(fm, "source_date") or "",
    }


# ── Deliverable 1: markdowns index ───────────────────────────────────────────

def build_markdowns_index() -> str:
    """Scan markdowns/ and return the full markdown text of the index."""
    entries = []
    for p in sorted(_MARKDOWNS_DIR.glob("*.md")):
        size = p.stat().st_size
        entries.append((p.name, size))

    lines = [
        "# Raw Source Corpus Index — `markdowns/`",
        "",
        "> **IMMUTABLE raw corpus.** Files in `markdowns/` are never modified by agents or",
        "> scripts — they are the original books, papers, and research reports ingested into",
        "> the system. All agent-generated content lives in `wiki/` instead.",
        "",
        f"Total: **{len(entries)} files**",
        "",
        "| Filename | Size |",
        "| --- | --- |",
    ]
    for name, size in entries:
        lines.append(f"| `{name}` | {_human_size(size)} |")

    lines.append("")
    lines.append(
        "_Generated by `tools/build_indexes.py`. Re-run after adding new raw sources._"
    )
    return "\n".join(lines) + "\n"


# ── Deliverable 2: investment memos index ────────────────────────────────────

def _publisher_prefix(slug: str) -> str:
    """Identify publisher from slug prefix (matches known registry keys)."""
    for pub in _PUBLISHER_ORDER:
        if slug.startswith(pub + "-") or slug == pub:
            return pub
    # Fallback: everything before the first dash
    return slug.split("-")[0]


def build_investment_memos_index() -> str:
    """Scan wiki/sources/ for memo cards and return the full markdown text of the index."""
    # Parse all source cards.
    cards = []
    for p in sorted(_WIKI_SOURCES_DIR.glob("*.md")):
        card = _parse_source_card(p)
        if card is None:
            continue
        if card["source_type"] != "memo":
            continue
        cards.append(card)

    # Group by publisher prefix.
    groups: dict[str, list[dict]] = {pub: [] for pub in _PUBLISHER_ORDER}
    other: list[dict] = []
    for card in cards:
        pub = _publisher_prefix(card["slug"])
        if pub in groups:
            groups[pub].append(card)
        else:
            other.append(card)

    lines = [
        "# Ingested Investor Memos Index",
        "",
        "All wiki source cards in `wiki/sources/` whose `source_type` is `memo`.",
        "Grouped by publisher. Re-run `tools/build_indexes.py` after a weekly pull to",
        "refresh counts.",
        "",
    ]

    total = 0
    for pub in _PUBLISHER_ORDER:
        group = groups[pub]
        if not group:
            continue
        # Pretty publisher label.
        label = pub.replace("-", " ").title()
        lines.append(f"## {label} ({len(group)})")
        lines.append("")
        for card in group:
            date_str = f" — {card['source_date']}" if card["source_date"] else ""
            lines.append(
                f"- **{card['title']}**  "
                f"slug: `{card['slug']}` | access: `{card['access_class']}`{date_str}"
            )
        lines.append("")
        total += len(group)

    if other:
        lines.append(f"## Other ({len(other)})")
        lines.append("")
        for card in other:
            date_str = f" — {card['source_date']}" if card["source_date"] else ""
            lines.append(
                f"- **{card['title']}**  "
                f"slug: `{card['slug']}` | access: `{card['access_class']}`{date_str}"
            )
        lines.append("")
        total += len(other)

    lines.append(f"---")
    lines.append(f"**Total memos: {total}**")
    lines.append("")
    lines.append(
        "_Generated by `tools/build_indexes.py`. Re-run after `tools/pull_all_sources.py`._"
    )
    return "\n".join(lines) + "\n"


# ── main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    _DOCS_DIR.mkdir(parents=True, exist_ok=True)

    markdowns_path = _DOCS_DIR / "markdowns-index.md"
    markdowns_content = build_markdowns_index()
    markdowns_path.write_text(markdowns_content, encoding="utf-8")
    print(f"Wrote {markdowns_path} ({len(markdowns_content):,} bytes)")

    memos_path = _DOCS_DIR / "investment-memos-index.md"
    memos_content = build_investment_memos_index()
    memos_path.write_text(memos_content, encoding="utf-8")
    print(f"Wrote {memos_path} ({len(memos_content):,} bytes)")


if __name__ == "__main__":
    main()
